name: 'Helm Package and Push'
description: 'Builds a Helm chart package and pushes it to a specified registry.'
inputs:
  chart_dir:
    description: 'Directory of the Helm chart to package.'
    required: true
  version:
    description: 'Version of the chart to package.'
    required: true
  registry_url:
    description: 'Helm registry URL to push the packaged chart.'
    required: true
  token:
    description: 'Token for logging into the Helm registry.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Helm
      shell: bash
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        
    - name: Helm dependency build
      shell: bash
      run: |
        helm dependency build ${{ inputs.chart_dir }}
        
    - name: Package Helm Chart
      shell: bash
      run: |
        helm package ${{ inputs.chart_dir }} --version ${{ inputs.version }} --app-version ${{ inputs.version }}
        
    - name: Log in to the Registry
      shell: bash
      run: |
        echo ${{ inputs.token }} | helm registry login ${{ inputs.registry_url }} --username USERNAME --password-stdin
        
    - name: Push Helm Chart to Registry
      shell: bash
      run: |
        CHART_PACKAGE=$(helm package ${{ inputs.chart_dir }} --version ${{ inputs.version }} | cut -d ":" -f 2 | xargs)
        helm push $CHART_PACKAGE oci://${{ inputs.registry_url }}
