name: Test Helm Package and Push

on: [push]
env:
  chart_dir: './test-chart'
  version: '1.0.0'
  registry_url: 'us-east1-docker.pkg.dev/face-swipe-app'

jobs:
  test-helm-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          root_url=$(echo $registry_url | awk -F/ '{print $3}')
          echo "helm registry login ${root_url}"
          echo -n '${{ secrets.GCP_SA_KEY }}' | helm registry login -u "_json_key_base64" --password-stdin "https://${root_url}"
      - name: Run Helm Package and Push Action
        uses: ./ # the action in the current checout
        with:
          chart_dir: ${{ env.chart_dir }}
          version: ${{ env.version }}
          registry_url: ${{ env.registry_url }}
          